default:
  path: "/"
  methods: ["GET"]
  controller: App\Controller\HomeController@index
  options: { sitemap: true }

post.view:
  path: "/post/{slug}/{id}"
  methods: ["GET"]
  controller: App\Controller\PostController@get

contact:
  path: "/contact"
  methods: ["GET"]
  controller: App\Controller\ContactController@index
  options: { sitemap: true }

contact.post:
  path: "/contact"
  methods: ["POST"]
  controller: App\Controller\ContactController@send

sitemap:
  path: "/sitemap.xml"
  methods: ["GET"]
  controller: App\Controller\SitemapController@index
  options: { sitemap: false }

login:
  path: "/login"
  methods: ["GET"]
  controller: App\Controller\LoginController@index
  options: { sitemap: true }

login.post:
  path: "/login"
  methods: ["POST"]
  controller: App\Controller\LoginController@login
  options: { sitemap: false }

logout:
  path: "/logout"
  methods: ["GET"]
  controller: App\Controller\LoginController@logout
  options: { sitemap: true }